name: Release
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: "1.18"

    - name: Build
      run: make


    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build artifacts
      run: |
        go version
        go install github.com/mitchellh/gox@latest
        export version=${{ github.ref }}
        make cross

    - name: Upload Darwin ARM/M1 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/darwin_arm64_kd
        asset_name: darwin_arm64_kd

    - name: Upload Darwin x64 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/darwin_amd64_kd
        asset_name: darwin_amd64_kd

    - name: Upload Linux x64 artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/linux_amd64_kd
        asset_name: linux_amd64_kd
